[package]
name = "spider-web"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thrussh = "0.33.5"
socket2 = "0.4.4"
config = "0.13.1"
